spring.application.name=carcare
spring.profiles.active=dev

# Puerto por donde escucha el servidor cuando se inicie
server.port=8080

# Path de la web API
spring.data.rest.base-path=/api

# Lengua local del proyecto
spring.web.locale=es_ES
spring.web.locale-resolver=fixed

# Versión de la API
spring.application.version=1.0.0

# Google Maps API Key (para gasolineras)
google.maps.api.key=temp_key